# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'

target 'Core' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  workspace 'Core'

  # Pods for Core
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'Alamofire'
  pod 'Kingfisher'
  pod 'Common', :git => "https://github.com/kevinhardianto6/Common.git", :tag => '1.0.2'

  target 'CoreTests' do
    # Pods for testing
  end

end